version: '3.8'

services:
  jedi-syslogger:
    build: .
    container_name: jedi-syslogger
    ports:
      - "8042:8042"
    volumes:
      - jedi-data:/app/data
      - ./custom_templates:/app/custom_templates
    restart: unless-stopped
    environment:
      - FLASK_ENV=production

volumes:
  jedi-data: